[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc", "pkg-config"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate",
    "python manage.py create_superuser_if_none_exists"
]

[start]
cmd = "python -m gunicorn payment_project.wsgi:application --bind 0.0.0.0:$PORT"
