services:
  # Django Web Service
  - type: web
    name: paystack-payment-app
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn payment_project.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: paystack-payment-db
          property: connectionString
      # Paystack Configuration (You'll need to add these manually in Render dashboard)
      # - key: PAYSTACK_SECRET_KEY
      #   value: your_paystack_secret_key
      # - key: PAYSTACK_PUBLIC_KEY
      #   value: your_paystack_public_key
      - key: PAYSTACK_BASE_URL
        value: https://api.paystack.co
      # Frontend and Backend URLs (update these with your actual URLs)
      - key: FRONTEND_CALLBACK_URL
        value: https://yourfrontend.com/payment/callback
      - key: BACKEND_WEBHOOK_URL
        sync: false
        value: https://paystack-payment-app.onrender.com/api/payments/webhook/
      # CORS Configuration
      - key: CORS_ALLOW_ALL_ORIGINS
        value: false
      - key: RENDER_EXTERNAL_URL
        value: https://paystack-payment-app.onrender.com
    
  # PostgreSQL Database
  - type: pgsql
    name: paystack-payment-db
    databaseName: paystack_payment
    user: paystack_user
    region: oregon
    plan: free
