services:
  - type: web
    name: paystack-payment-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn payment_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: paystack-payment-db
          property: connectionString

databases:
  - name: paystack-payment-db
    databaseName: paystack_payment
    user: paystack_user
