"""
Django settings for payment_project project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-_)r2%ikc=k10t3b@3w6y*0@rre^x9val^eut@($uur83ytq(i=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS configuration
if DEBUG:
    # Development
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
else:
    # Production - Render provides RENDER_EXTERNAL_HOSTNAME
    ALLOWED_HOSTS = [config('RENDER_EXTERNAL_HOSTNAME', default='localhost')]
    # Also allow custom hosts from environment
    custom_hosts = config('ALLOWED_HOSTS', default='')
    if custom_hosts:
        ALLOWED_HOSTS.extend([host.strip() for host in custom_hosts.split(',') if host.strip()])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    # "django_ratelimit",  # Temporarily disabled - enable with Redis
    # Local apps
    "payments.apps.PaymentsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "payment_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "payment_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration - PostgreSQL Only
import dj_database_url
import os

# Check if DATABASE_URL is available
database_url = os.environ.get('DATABASE_URL')
if database_url:
    print(f"[DATABASE] Found DATABASE_URL: {database_url[:20]}...")
    # Use DATABASE_URL for both development and production
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    
    # Add SSL requirement for production
    if not DEBUG:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'require',
        }
else:
    print("[DATABASE] No DATABASE_URL found, using individual PostgreSQL settings")
    # Use individual PostgreSQL settings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='payment_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432', cast=int),
            'OPTIONS': {
                'connect_timeout': 20,
            },
        }
    }
    
    # In production, DATABASE_URL should always be provided
    if not DEBUG:
        raise ValueError(
            "DATABASE_URL environment variable is required in production. "
            "Make sure your Render PostgreSQL database is connected."
        )

# Print database configuration for debugging
print(f"[DATABASE] Engine: {DATABASES['default']['ENGINE']}")
print(f"[DATABASE] Name: {DATABASES['default']['NAME']}")
if 'HOST' in DATABASES['default']:
    print(f"[DATABASE] Host: {DATABASES['default']['HOST']}")
print(f"[DATABASE] Using DATABASE_URL: {bool(database_url)}")
print(f"[DATABASE] Debug mode: {DEBUG}")

# Local memory cache (for development - works without Redis)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "payment-cache",
    }
}

# Redis cache configuration (uncomment when Redis is installed)
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }

# Rate limiting configuration (disabled for now - enable with Redis)
# RATELIMIT_USE_CACHE = 'default'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Payment API',
    'DESCRIPTION': 'Django Paystack Payment Integration API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://127.0.0.1:3000",
]

# Allow all origins in production if CORS_ALLOW_ALL_ORIGINS is set
if config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool):
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Add Render domain from environment
    render_url = config('RENDER_EXTERNAL_URL', default='')
    if render_url:
        CORS_ALLOWED_ORIGINS.append(render_url)

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]

# Add Render domain to CSRF trusted origins
if not DEBUG:
    render_url = config('RENDER_EXTERNAL_URL', default='')
    if render_url:
        CSRF_TRUSTED_ORIGINS.append(render_url)
    
    # Add common Render domain patterns
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.onrender.com',
        'http://*.onrender.com'
    ])

# Add custom trusted origins
custom_origins = config('CSRF_TRUSTED_ORIGINS', default='').split(',')
for origin in custom_origins:
    if origin.strip():
        CSRF_TRUSTED_ORIGINS.append(origin.strip())

# Paystack settings with error handling
try:
    PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
    PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
except Exception as e:
    print(f"[WARNING] Paystack keys not found: {e}")
    PAYSTACK_SECRET_KEY = 'dummy-key-for-startup'
    PAYSTACK_PUBLIC_KEY = 'dummy-key-for-startup'

PAYSTACK_BASE_URL = config('PAYSTACK_BASE_URL', default='https://api.paystack.co')

# Application URLs
FRONTEND_CALLBACK_URL = config('FRONTEND_CALLBACK_URL', default='http://localhost:3000/payment/callback')
BACKEND_WEBHOOK_URL = config('BACKEND_WEBHOOK_URL', default='http://localhost:8000/api/payments/webhook/')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'console_debug': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'payments.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
